### ISSUE TITLE
Particles being black after jumping of screen

### ISSUE THREAD

**Issue by staadecker** [SUPERETDUPER/Robotics-2018#5]

**Comment by staadecker** [comment]
`ERROR : Updater : SurfaceMap : x : 439. y : 1178 java.lang.ArrayIndexOutOfBoundsException: Coordinate out of bounds!
Exception in thread "Updater" java.lang.IndexOutOfBoundsException: x : 439. y : 1178 java.lang.ArrayIndexOutOfBoundsException: Coordinate out of bounds!
	at common.mapping.SurfaceMap.getColorAtPoint(SurfaceMap.java:44)
	at ev3.robot.sim.SimColorSensors.getColorSurfaceLeft(SimColorSensors.java:26)
	at ev3.localization.RobotPoseProvider$Updater.run(RobotPoseProvider.java:180)`
